#Tasks here
#File can include smaller files if warranted
- name: Check packages installation in Debian
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{packages}}"
  when: "ansible_facts['os_family'] == 'Debian'"
  become: true

- name: Check installation in RedHat
  dnf:
    name: "{{ item }}"
    state: present
    with_items: "{{ packages }}"
  when: "ansible_facts['os_family'] == 'RedHat'"
  become: true

- name: Enable postgresql in systemd
  systemd:
    name: postgresql.service
    enabled: true

- name: Start Postgress
  ansible.builtin.shell: "pg_ctlcluster start $(pg_conftool --short show cluster_name | sed 's,/, ,')"
  become: true

- name: Check if pgrx required
  ansible.builtin.include_tasks: 'install_pgrx.yml'
  when: "'pgrx' in modules"

#- name: Install pr




